extend = "ruff-base.toml"

# These are files to exclude for this project.
extend-exclude = [
  # "**/*.ipynb",  # commonly not ruff-compliant
  "docs",
  "update_characteristics.py",
  "calc_si_align.py",
  "derive_via_ofls_eqns.py",
  "pog_absolute_pointing.py",
  "absolute_pointing_uncertainty.ipynb",
  "aimpoint_jumps.ipynb",
  "asol_to_chip_transforms.ipynb",
  "testing/**/*.ipynb",
  "fit_aimpoint_drift.ipynb",
  "fit_aimpoint_drift-2018-11.ipynb",
  "fit_aimpoint_drift-2021-01.ipynb",
  "fit_aimpoint_drift-2021-03.ipynb",
  "fit_aimpoint_drift-2022-11.ipynb",
]

# These are rules that commonly cause many ruff warnings. Code will be improved by
# incrementally fixing code to adhere to these rules, but for practical purposes they
# can be ignored by uncommenting each one. You can also add to this list as needed.
lint.extend-ignore = [
  "B905", # `zip()` without an explicit `strict=` parameter
  # "PLC1901", # compare-to-empty-string
  # "PLR0911", # Too many returns
  # "PLR0912", # Too many branches
  "PLW0603", # Global statement
  "D205", # Missing blank line after summary
  "PLR0915", # Too many statements
  # "PGH004", # Use specific rule codes when using `noqa`
  # "C401", # Unnecessary generator (rewrite as a `set` comprehension)
  # "C402", # Unnecessary generator (rewrite as a dict comprehension)
  # "C405", # Unnecessary `list` literal (rewrite as a `set` literal)
  # "C408", # Unnecessary `dict` call (rewrite as a literal)
  # "C416", # Unnecessary `dict` comprehension (rewrite using `dict()`)
  # "G010", # warn is deprecated in favor of warning
  # "PYI056", # Calling `.append()` on `__all__` may not be supported by all type checkers
]
